---
title: "Graduate School Admissions"
author: "Jasmin Capka"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Aggregated Binomial

```{r load data}
data(UCBadmit)
d <-UCBadmit
```

```{r construct data}
dat_list <- list(
  admit = d$admit,
  applications = d$applications,
  gid = ifelse(d$applicant.gender == "male", 1, 2)
)
m11.7 <- ulam(alist(admit ~ dbinom(applications, p),
                    logit(p) <- a[gid],
                    a[gid] ~ dnorm(0, 1.5)) ,
              data = dat_list,
              chains = 4)
precis(m11.7, depth = 2)
```

Compute differences between male and female:
```{r}
post <-extract.samples(m11.7)
diff_a <-post$a[,1]-post$a[,2]
diff_p <-inv_logit(post$a[,1])-inv_logit(post$a[,2])
precis( list(diff_a=diff_a,diff_p=diff_p))
```

Posterior check function:

```{r}
postcheck( m11.7)
# draw lines connecting points from same dept
for (i in 1:6){
x <-1+2*(i-1)
y1 <-d$admit[x]/d$applications[x]
y2 <-d$admit[x+1]/d$applications[x+1]
lines( c(x,x+1),c(y1,y2),col=rangi2,lwd=2)
text( x+0.5,(y1+y2)/2+0.05,d$dept[x],cex=0.8,col=rangi2)
}
```

New model with regard too department:

```{r}
dat_list$dept_id <-rep(1:6,each=2)
m11.8 <-ulam(
alist(
admit ~dbinom(applications,p),
logit(p) <-a[gid]+delta[dept_id],
a[gid] ~dnorm(0,1.5),
delta[dept_id] ~dnorm(0,1.5)
) ,data=dat_list,chains=4,iter=4000)
precis( m11.8,depth=2)
```

Calculate differences:

```{r}
post <-extract.samples(m11.8)
diff_a <-post$a[,1]-post$a[,2]
diff_p <-inv_logit(post$a[,1])-inv_logit(post$a[,2])
precis( list(diff_a=diff_a,diff_p=diff_p))
```

Show different raw application rates:

```{r}
pg <-with(dat_list,sapply(1:6,function(k)
applications[dept_id==k]/sum(applications[dept_id==k]) ))
rownames(pg) <-c("male","female")
colnames(pg) <-unique(d$dept)
round( pg,2)
```

Inspect posterior:

```{r}
postcheck(m11.8)
```

```{r}
pairs(m11.8)
```









































