---
title: "Poisson Distribution"
author: "Jasmin Capka"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Oceanic Tool Complexity

```{r load data}
data(Kline)
d <-Kline
d
```

Make new columns:

```{r}
d$P <-scale(log(d$population))
d$contact_id <-ifelse(d$contact=="high",2,1)
```

### Priors

```{r}
curve( dlnorm(x,0,10),from=0,to=100,n=200)
```

```{r}
curve( dlnorm(x,3,0.5),from=0,to=100,n=200)
```

Prior for beta:

```{r}
N <-100
a <-rnorm(N,3,0.5)
b <-rnorm(N,0,10)
plot( NULL,xlim=c(-2,2),ylim=c(0,100))
for (i in 1:N)curve(exp(a[i]+b[i]*x),add=TRUE,col=grau())
```

Choosing tighter prior:

```{r}
set.seed(10)
N <-100
a <-rnorm(N,3,0.5)
b <-rnorm(N,0,0.2)
plot( NULL,xlim=c(-2,2),ylim=c(0,100))
for (i in 1:N)curve(exp(a[i]+b[i]*x),add=TRUE,col=grau())
```

With non standardized log population:

```{r}
x_seq <-seq(from=log(100),to=log(200000),length.out=100)
lambda <-sapply(x_seq,function(x)exp(a+b*x))
plot( NULL,xlim=range(x_seq),ylim=c(0,500),xlab="log population",
ylab="total tools")
for (i in 1:N)lines(x_seq,lambda[i,],col=grau(),lwd=1.5)
```

With normal population:

```{r}
plot( NULL,xlim=range(exp(x_seq)),ylim=c(0,500),xlab="population",
ylab="total tools")
for (i in 1:N)lines(exp(x_seq),lambda[i,],col=grau(),lwd=1.5)
```

### Approximate posterior

```{r}
dat <- list(T = d$total_tools,
            P = d$P,
            cid = d$contact_id)

# intercept only
m11.9 <- ulam(
  alist(
    T ~ dpois(lambda),
    log(lambda) <- a,
    a ~ dnorm(3, 0.5)),
  data = dat,
  chains = 4,
  log_lik = TRUE
)

# interaction model
m11.10 <- ulam(
  alist(
    T ~ dpois(lambda),
    log(lambda) <- a[cid] + b[cid] * P,
    a[cid] ~ dnorm(3, 0.5),
    b[cid] ~ dnorm(0, 0.2)
  ),
  data = dat,
  chains = 4,
  log_lik = TRUE
)
```

Compare the models:

```{r}
compare( m11.9,m11.10,func=PSIS)
```

### Plot posterior predictions

```{r}
k <-PSIS(m11.10,pointwise=TRUE)$k
plot( dat$P,dat$T,xlab="log population (std)",ylab="total tools",
col=rangi2 ,pch=ifelse(dat$cid==1,1,16),lwd=2,
ylim=c(0,75) ,cex=1+normalize(k))

# set up the horizontal axis values to compute predictions at
ns <-100
P_seq <-seq(from=-1.4,to=3,length.out=ns)

# predictions for cid=1 (low contact)
lambda <-link(m11.10,data=data.frame(P=P_seq,cid=1))
lmu <-apply(lambda,2,mean)
lci <-apply(lambda,2,PI)
lines( P_seq,lmu,lty=2,lwd=1.5)
shade( lci,P_seq,xpd=TRUE)

# predictions for cid=2 (high contact)
lambda <-link(m11.10,data=data.frame(P=P_seq,cid=2))
lmu <-apply(lambda,2,mean)
lci <-apply(lambda,2,PI)
lines( P_seq,lmu,lty=1,lwd=1.5)
shade( lci,P_seq,xpd=TRUE)
```

On a normal scale:

```{r}
plot( d$population,d$total_tools,xlab="population",ylab="total tools",
col=rangi2 ,pch=ifelse(dat$cid==1,1,16),lwd=2,
ylim=c(0,75) ,cex=1+normalize(k))

ns <-100
P_seq <-seq(from=-5,to=3,length.out=ns)
# 1.53 is sd of log(population)
# 9 is mean of log(population)
pop_seq <-exp(P_seq*1.53+9)

lambda <-link(m11.10,data=data.frame(P=P_seq,cid=1))
lmu <-apply(lambda,2,mean)
lci <-apply(lambda,2,PI)
lines( pop_seq,lmu,lty=2,lwd=1.5)
shade( lci,pop_seq,xpd=TRUE)

lambda <-link(m11.10,data=data.frame(P=P_seq,cid=2))
lmu <-apply(lambda,2,mean)
lci <-apply(lambda,2,PI)
lines( pop_seq,lmu,lty=1,lwd=1.5)
shade( lci,pop_seq,xpd=TRUE)
```

## Monastery (Exposure and the offset)

Own monastery:

```{r}
num_days <-30
y <-rpois(num_days,1.5)
```

Other monastery:

```{r}
num_weeks <-4
y_new <-rpois(num_weeks,0.5*7)
```

Build df to organize:

```{r}
y_all <-c(y,y_new)
exposure <-c(rep(1,30),rep(7,4))
monastery <-c(rep(0,30),rep(1,4))
d <-data.frame(y=y_all,days=exposure,monastery=monastery)
```

Create model:

```{r}
# compute the offset
d$log_days <-log(d$days)

# fit the model
m11.12 <-quap(
alist(
y ~dpois(lambda),
log(lambda) <-log_days+a+b*monastery,
a ~dnorm(0,1),
b ~dnorm(0,1)
), data=d)
```

Compare:

```{r}
post <-extract.samples(m11.12)
lambda_old <-exp(post$a)
lambda_new <-exp(post$a+post$b)
precis( data.frame(lambda_old,lambda_new))
```






















