---
title: "Prosocial Chimpanzees"
author: "Jasmin Capka"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Logistic Regression

```{r load data}
data(chimpanzees)
d <- chimpanzees
```

```{r index variable}
d$treatment <- 1 + d$prosoc_left + 2 * d$condition
```

```{r verify}
xtabs(~treatment + prosoc_left + condition, d)
```

### Picking priors

```{r flat prior}
m11.1 <- quap(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a,
    a ~ dnorm(0, 10)
  ), data = d)
```

```{r sample from prior}
set.seed(1999)
prior <- extract.prior(m11.1, n = 1e4)
```

```{r density plot}
p <- inv_logit(prior$a)
dens(p, adj = 0.1)
```

```{r finding prior for b}
m11.2 <- quap(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a + b[treatment],
    a ~ dnorm(0, 1.5),
    b[treatment] ~ dnorm(0, 10)
  ), data = d)

set.seed(1999)

prior <- extract.prior(m11.2, n = 1e4)
p <- sapply(1:4, function(k)inv_logit(prior$a + prior$b[, k]))
```

```{r absolute prior difference between first two treatments}
dens(abs(p[, 1] - p[, 2]), adj = 0.1)
```

```{r average prior difference for 0.5}
m11.3 <- quap(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a + b[treatment],
    a ~ dnorm(0, 1.5),
    b[treatment] ~ dnorm(0, 0.5)
  ), data = d)
set.seed(1999)
prior <- extract.prior(m11.3, n = 1e4)
p <- sapply(1:4, function(k)inv_logit(prior$a + prior$b[, k]))
mean(abs(p[, 1] - p[, 2]))
```

```{r prepare data list for quap}
# trimmed data list
dat_list <- list(
  pulled_left = d$pulled_left,
  actor = d$actor,
  treatment = as.integer(d$treatment))
```

```{r ulam model}
m11.4 <- ulam(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a[actor] + b[treatment],
    a[actor] ~ dnorm(0, 1.5),
    b[treatment] ~ dnorm(0, 0.5)
  ), data = dat_list, chains = 4, log_lik = TRUE)
precis(m11.4, depth = 2)
```

```{r compare actor}
post <- extract.samples(m11.4)
p_left <- inv_logit(post$a)
plot(precis(as.data.frame(p_left)), xlim = c(0, 1))
```

```{r consider treatment effects}
labs <- c("R/N", "L/N", "R/P", "L/P")
plot(precis(m11.4, depth = 2, pars = "b"), labels = labs)
```

```{r calculate differences}
diffs <- list(
  db13 = post$b[, 1] - post$b[, 3],
  db24 = post$b[, 2] - post$b[, 4])
plot(precis(diffs))
```

```{r calculate proportion of each combination of actor and treatment}
pl <- by(d$pulled_left, list(d$actor, d$treatment), mean)
pl[1,]
```

```{r plot data}
plot(NULL, xlim = c(1, 28), ylim = c(0, 1), xlab = "",
     ylab = "proportion leftlever", xaxt = "n", yaxt = "n")
axis(2, at = c(0, 0.5, 1), labels = c(0, 0.5, 1))
abline(h = 0.5, lty = 2)
for (j in 1:7)abline(v = (j - 1) * 4 + 4.5, lwd = 0.5)
for (j in 1:7)text((j - 1) * 4 + 2.5, 1.1, concat("actor", j), xpd = TRUE)
for (j in (1:7)[-2]) {
  lines((j - 1) * 4 + c(1, 3), pl[j, c(1, 3)], lwd = 2, col = rangi2)
  lines((j - 1) * 4 + c(2, 4), pl[j, c(2, 4)], lwd = 2, col = rangi2)
}
points(1:28, t(pl), pch = 16, col = "white", cex = 1.7)
points(1:28, t(pl), pch = c(1, 1, 16, 16), col = rangi2, lwd = 2)
yoff <- 0.01
text(1, pl[1, 1] - yoff, "R/N", pos = 1, cex = 0.8)
text(2, pl[1, 2] + yoff, "L/N", pos = 3, cex = 0.8)
text(3, pl[1, 3] - yoff, "R/P", pos = 1, cex = 0.8)
text(4, pl[1, 4] + yoff, "L/P", pos = 3, cex = 0.8)
mtext("observedproportions\n")
```

```{r}
dat <- list(actor = rep(1:7, each = 4), treatment = rep(1:4, times = 7))
p_post <- link(m11.4, data = dat)
p_mu <- apply(p_post, 2, mean)
p_ci <- apply(p_post, 2, PI)
```

### Model with different index variables for prosocial option and partner

```{r}
d$side <- d$prosoc_left + 1  #right 1, left 2
d$cond <- d$condition + 1  # no partner 1, partner 2
```

```{r new model}
dat_list2 <- list(
  pulled_left = d$pulled_left,
  actor = d$actor,
  side = d$side,
  cond = d$cond)
m11.5 <- ulam(
  alist(
    pulled_left ~ dbinom(1, p),
    logit(p) <- a[actor] + bs[side] + bc[cond],
    a[actor] ~ dnorm(0, 1.5),
    bs[side] ~ dnorm(0, 0.5),
    bc[cond] ~ dnorm(0, 0.5)
  ), data = dat_list2, chains = 4, log_lik = TRUE)
```

```{r compare models}
compare(m11.5, m11.4, func = PSIS)
```

### Relative and absolute measures

```{r}
post <- extract.samples(m11.4)
mean(exp(post$b[, 4] - post$b[, 2]))
```

## Aggragated binomial

```{r number of times lever was pulled}
data(chimpanzees)
d <- chimpanzees
d$treatment <- 1 + d$prosoc_left + 2 * d$condition
d$side <- d$prosoc_left + 1 # right 1, left 2
d$cond <- d$condition + 1 # no partner 1, partner 2
d_aggregated <- aggregate(
  d$pulled_left,
  list(treatment = d$treatment, actor = d$actor,
       side = d$side, cond = d$cond),
  sum)
colnames(d_aggregated)[5] <- "left_pulls"
```

```{r data and model}
dat <- with(d_aggregated, list(
  left_pulls = left_pulls,
  treatment = treatment,
  actor = actor,
  side = side,
  cond = cond))
m11.6 <- ulam(
  alist(
    left_pulls ~ dbinom(18, p),
    logit(p) <- a[actor] + b[treatment],
    a[actor] ~ dnorm(0, 1.5),
    b[treatment] ~ dnorm(0, 0.5)
  ), data = dat, chains = 4, log_lik = TRUE)
```

```{r}
compare( m11.6,m11.4,func=PSIS)
```

Explanation for difference in PSIS:
```{r}
# deviance of aggregated 6-in-9
-2*dbinom(6,9,0.2,log=TRUE)
# deviance of dis-aggregated
-2*sum(dbern(c(1,1,1,1,1,1,0,0,0),0.2,log=TRUE))
```
































