---
title: "Building an Interaction"
author: "Jasmin Capka"
date: "11/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Making a rugged model

```{r load data, preprocessing}
data(rugged)
d <- rugged

# make log version of outcome
d$log_gdp <- log(d$rgdppc_2000)

# extract countries with GDP data
dd <- d[complete.cases(d$rgdppc_2000),]

# rescale variables
dd$log_gdp_std <- dd$log_gdp / mean(dd$log_gdp)
dd$rugged_std <- dd$rugged / max(dd$rugged)
```

```{r first simple model}
m8.1 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a + b * (rugged_std - 0.215),
    a ~ dnorm(1, 1),
    b ~ dnorm(0, 1),
    sigma ~ dexp(1)
  ), data = dd)
```

```{r have a look at prior and implied lines}
set.seed(7)
prior <- extract.prior(m8.1)
# set up the plot dimensions
plot(NULL, xlim = c(0, 1), ylim = c(0.5, 1.5), xlab = "ruggedness", ylab = "logGDP")
abline(h = min(dd$log_gdp_std), lty = 2)
abline(h = max(dd$log_gdp_std), lty = 2)
# draw 50 lines from the prior
rugged_seq <- seq(from = -0.1, to = 1.1, length.out = 30)
mu <- link(m8.1, post = prior, data = data.frame(rugged_std = rugged_seq))
for (i in 1:50)lines(rugged_seq, mu[i,], col = col.alpha("black", 0.3))
```

```{r new model}
m8.1 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a + b * (rugged_std - 0.215),
    a ~ dnorm(1, 0.1),
    b ~ dnorm(0, 0.3),
    sigma ~ dexp(1)
  ), data = dd)

precis(m8.1)
```

## Adding an indicator variable is not enough

```{r add africa index}
# make variable to index Africa (1) or not (2)
dd$cid <- ifelse(dd$cont_africa == 1, 1, 2)
```

```{r train model with continent}
m8.2 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a[cid] + b * (rugged_std - 0.215),
    a[cid] ~ dnorm(1, 0.1),
    b ~ dnorm(0, 0.3),
    sigma ~ dexp(1)
  ), data = dd)
```

```{r compare}
compare(m8.1, m8.2)

```

```{r inspect model}
precis(m8.2, depth = 2)
```

```{r difference between both intercepts}
post <- extract.samples(m8.2)
diff_a1_a2 <- post$a[, 1] - post$a[, 2]
PI(diff_a1_a2)
```

```{r}
rugged.seq <- seq(from = -0.1, to = 1.1, length.out = 30)
# compute mu over samples, fixing cid=2 and then cid=1
mu.NotAfrica <- link(m8.2,
                     data = data.frame(cid = 2, rugged_std = rugged.seq))
mu.Africa <- link(m8.2,
                  data = data.frame(cid = 1, rugged_std = rugged.seq))
# summarize to means andintervals
mu.NotAfrica_mu <- apply(mu.NotAfrica, 2, mean)
mu.NotAfrica_ci <- apply(mu.NotAfrica, 2, PI, prob = 0.97)
mu.Africa_mu <- apply(mu.Africa, 2, mean)
mu.Africa_ci <- apply(mu.Africa, 2, PI, prob = 0.97)
```


## Adding an interaction does work

```{r model with interaction}
m8.3 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a[cid] + b[cid] * (rugged_std - 0.215),
    a[cid] ~ dnorm(1, 0.1),
    b[cid] ~ dnorm(0, 0.3),
    sigma ~ dexp(1)
  ), data = dd)
```

```{r inspect}
precis(m8.3, depth = 2)
```

```{r compare}
compare(m8.1, m8.2, m8.3, func = PSIS)
```

```{r plot PSIS pareto k values}
plot(PSIS(m8.3, pointwise = TRUE)$k)
```

## Plotting the interaction

```{r plot}
# plot Africa - cid=1
d.A1 <- dd[dd$cid == 1,]
plot(d.A1$rugged_std, d.A1$log_gdp_std, pch = 16, col = rangi2,
     xlab = "ruggedness (standardized)", ylab = "log GDP (as proportion of mean)",
     xlim = c(0, 1))
mu <- link(m8.3, data = data.frame(cid = 1, rugged_std = rugged_seq))
mu_mean <- apply(mu, 2, mean)
mu_ci <- apply(mu, 2, PI, prob = 0.97)
lines(rugged_seq, mu_mean, lwd = 2)
shade(mu_ci, rugged_seq, col = col.alpha(rangi2, 0.3))
mtext("African nations")
# plotnon-Africa-cid=2
d.A0 <- dd[dd$cid == 2,]
plot(d.A0$rugged_std, d.A0$log_gdp_std, pch = 1, col = "black",
     xlab = "ruggedness (standardized)", ylab = "log GDP (as proportion of mean)",
     xlim = c(0, 1))
mu <- link(m8.3, data = data.frame(cid = 2, rugged_std = rugged_seq))
mu_mean <- apply(mu, 2, mean)
mu_ci <- apply(mu, 2, PI, prob = 0.97)
lines(rugged_seq, mu_mean, lwd = 2)
shade(mu_ci, rugged_seq)
mtext("Non-African nations")
```

