---
title: "Building an Interaction"
author: "Jasmin Capka"
date: "11/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## A winter flower

```{r load data}
data(tulips)
d <- tulips
str(d)
```

## The models

```{r standardize}
d$blooms_std <- d$blooms / max(d$blooms)
d$water_cent <- d$water - mean(d$water)
d$shade_cent <- d$shade - mean(d$shade)
```

```{r first simple model}
m8.4 <- quap(
  alist(
    blooms_std ~ dnorm(mu, sigma),
    mu <- a + bw * water_cent + bs * shade_cent,
    a ~ dnorm(0.5, 0.25),
    bw ~ dnorm(0, 0.25),
    bs ~ dnorm(0, 0.25),
    sigma ~ dexp(1)
  ), data = d)
```

```{r new model with interaction}
m8.5 <- quap(
  alist(
    blooms_std ~ dnorm(mu, sigma),
    mu <- a +
      bw * water_cent +
      bs * shade_cent +
      bws * water_cent * shade_cent,
    a ~ dnorm(0.5, 0.25),
    bw ~ dnorm(0, 0.25),
    bs ~ dnorm(0, 0.25),
    bws ~ dnorm(0, 0.25),
    sigma ~ dexp(1)
  ), data = d)
```

## Plotting posterior predictions

```{r plot for simple model}
par(mfrow = c(1, 3)) #3 plots in 1 row
for (s in -1:1) {
  idx <- which(d$shade_cent == s)
  plot(d$water_cent[idx], d$blooms_std[idx], xlim = c(-1, 1), ylim = c(0, 1),
       xlab = "water", ylab = "blooms", pch = 16, col = rangi2)
  mu <- link(m8.4, data = data.frame(shade_cent = s, water_cent = -1:1))
  for (i in 1:20)lines(-1:1, mu[i,], col = col.alpha("black", 0.3))
}
```

```{r plot for interaction model}
par(mfrow = c(1, 3)) #3 plots in 1 row
for (s in -1:1) {
  idx <- which(d$shade_cent == s)
  plot(d$water_cent[idx], d$blooms_std[idx], xlim = c(-1, 1), ylim = c(0, 1),
       xlab = "water", ylab = "blooms", pch = 16, col = rangi2)
  mu <- link(m8.5, data = data.frame(shade_cent = s, water_cent = -1:1))
  for (i in 1:20)lines(-1:1, mu[i,], col = col.alpha("black", 0.3))
}
```

## Plotting prior predictions

```{r extract prior}
set.seed(7)
prior <- extract.prior(m8.5)
```

```{r plot for interaction model}
par(mfrow = c(1, 3)) # 3 plots in 1 row
for (s in -1:1) {
  idx <- which(d$shade_cent == s)
  plot(d$water_cent[idx], d$blooms_std[idx], xlim = c(-1, 1), ylim = c(0, 1),
       xlab = "water", ylab = "blooms", pch = 16, col = rangi2)
  mu <- link(m8.5, data = data.frame(shade_cent = s, water_cent = -1:1), post=prior)
  for (i in 1:20)lines(-1:1, mu[i,], col = col.alpha("black", 0.3))
}
```
