---
title: "good King Markov and His Island Kingdom"
author: "Jasmin Capka"
date: "11/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Good King Markov

```{r Simulate King Markov algorithm}
num_weeks <-1e5
positions <-rep(0,num_weeks)
current <-10
for (i in 1:num_weeks){
  ## record current position
  positions[i] <-current
  ## flip coin to generate proposal
  proposal <-current+sample(c(-1,1),size=1)
  ## now make sure he loops around the archipelago
  if (proposal<1)proposal<-10
  if (proposal>10)proposal<-1
  ## move?
  prob_move <-proposal/current
  current <-ifelse(runif(1)<prob_move,proposal,current)
}
```

```{r plot travels}
plot( 1:100,positions[1:100])
plot( table(positions))
```

## Metropolis algorithm

```{r}
D <-10
T <-1e3
Y <-rmvnorm(T,rep(0,D),diag(D))
rad_dist <-function(Y)sqrt(sum(Y^2))
Rd <-sapply(1:T,function(i)rad_dist(Y[i,]))
dens( Rd)
```

## Easy Hamiltonian Monte Carlo:ulam

```{r}
library(rethinking)
data(rugged)
d <-rugged
d$log_gdp <-log(d$rgdppc_2000)
dd <-d[complete.cases(d$rgdppc_2000),]
dd$log_gdp_std <-dd$log_gdp/mean(dd$log_gdp)
dd$rugged_std <-dd$rugged/max(dd$rugged)
dd$cid <-ifelse(dd$cont_africa==1,1,2)
```

```{r model with quap}
m8.3 <-quap(
alist(
log_gdp_std ~dnorm(mu,sigma),
mu <-a[cid]+b[cid]*(rugged_std-0.215),
a[cid] ~dnorm(1,0.1),
b[cid] ~dnorm(0,0.3),
sigma ~dexp(1)
) ,data=dd)
precis( m8.3,depth=2)
```

```{r preprocessing}
dat_slim <-list(
log_gdp_std =dd$log_gdp_std,
rugged_std =dd$rugged_std,
cid =as.integer(dd$cid)
)
str(dat_slim)
```

```{r}
m9.1 <-ulam(
alist(
log_gdp_std ~dnorm(mu,sigma),
mu <-a[cid]+b[cid]*(rugged_std-0.215),
a[cid] ~dnorm(1,0.1),
b[cid] ~dnorm(0,0.3),
sigma ~dexp(1)
) ,data=dat_slim,chains=1)
```

```{r summarize}
precis( m9.1,depth=2)
```

```{r run several chains}
m9.1 <- ulam(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a[cid] + b[cid] * (rugged_std - 0.215),
    a[cid] ~ dnorm(1, 0.1),
    b[cid] ~ dnorm(0, 0.3),
    sigma ~ dexp(1)
  ) ,
  data = dat_slim,
  chains = 4,
  cores = 4
)
```

```{r compare chains}
show( m9.1)
```

```{r summarize new model}
precis(m9.1, 2)
```

```{r visualize}
pairs( m9.1)
```

```{r inspect chain}
traceplot( m9.1, chain=1)
```
```{r trank plot}
trankplot( m9.1)
```

### Taming a wild chain

```{r}
y <-c(-1,1)
set.seed(11)
m9.2 <-ulam(
alist(
y ~dnorm(mu,sigma),
mu <-alpha,
alpha ~dnorm(0,1000),
sigma ~dexp(0.0001)
) ,data=list(y=y),chains=3)
```

```{r}
precis( m9.2)
```

```{r}
pairs( m9.2@stanfit)
```

```{r}
traceplot(m9.2)
trankplot(m9.2)
```

```{r add weakly informative priors}
set.seed(11)
m9.3 <-ulam(
alist(
y ~dnorm(mu,sigma),
mu <-alpha,
alpha ~dnorm(1,10),
sigma ~dexp(1)
) ,data=list(y=y),chains=3)
precis( m9.3)
```

```{r}
traceplot(m9.3)
trankplot(m9.3)
```

### Non-identifiable parameters

```{r}
set.seed(41)
y <-rnorm(100,mean=0,sd=1)
```

```{r}
set.seed(384)
m9.4 <-ulam(
alist(
y ~dnorm(mu,sigma),
mu <-a1+a2,
a1 ~dnorm(0,1000),
a2 ~dnorm(0,1000),
sigma ~dexp(1)
) ,data=list(y=y),chains=3, cores=3)
precis( m9.4)
```

```{r}
traceplot(m9.4)
trankplot(m9.4)
```

```{r adjusted priors}
m9.5 <-ulam(
alist(
y ~dnorm(mu,sigma),
mu <-a1+a2,
a1 ~dnorm(0,10),
a2 ~dnorm(0,10),
sigma ~dexp(1)
) ,data=list(y=y),chains=3, cores = 3)
precis( m9.5)
```

```{r}
traceplot(m9.5)
trankplot(m9.5)
```