---
title: "Outliers and other Illusions"
author: "Jasmin Capka"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## WaffleHouse, Divorce models

```{r fir models}
data(WaffleDivorce)
d <-WaffleDivorce
d$A <-standardize(d$MedianAgeMarriage)
d$D <-standardize(d$Divorce)
d$M <-standardize(d$Marriage)
m5.1 <-quap(
alist(
D ~dnorm(mu,sigma),
mu <-a+bA*A,
a ~dnorm(0,0.2),
bA ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)
m5.2 <-quap(
alist(
D ~dnorm(mu,sigma),
mu <-a+bM*M,
a ~dnorm(0,0.2),
bM ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)
m5.3 <-quap(
alist(
D ~dnorm(mu,sigma),
mu <-a+bM*M+bA*A,
a ~dnorm(0,0.2),
bM ~dnorm(0,0.5),
bA ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)
```

## Scoring the right data
```{r compare with PSIS}
set.seed(24071847)
compare( m5.1,m5.2,m5.3,func=PSIS)
```

```{r state wise look at PSIS}
set.seed(24071847)
PSIS_m5.3 <-PSIS(m5.3,pointwise=TRUE)
set.seed(24071847)
WAIC_m5.3 <-WAIC(m5.3,pointwise=TRUE)
plot( PSIS_m5.3$k,WAIC_m5.3$penalty,xlab="PSIS Pareto k",
ylab="WAIC penalty",col=rangi2,lwd=2)
```

```{r reestimate with student t distribution}
m5.3t <-quap(
alist(
D ~dstudent(2,mu,sigma),
mu <-a+bM*M+bA*A,
a ~dnorm(0,0.2),
bM ~dnorm(0,0.5),
bA ~dnorm(0,0.5),
sigma ~dexp(1)
) ,data=d)
```

```{r new PSIS}
PSIS(m5.3t)
```
-> no warnings anymore


