---
title: "Ordered Categorical Outcomes"
author: "Jasmin Capka"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Moral intuition

Load data:

```{r}
data(Trolley)
d <-Trolley
```

## Describing an ordered distribution with intercepts

```{r}
simplehist( d$response,xlim=c(1,7),xlab="response")
```

compute cumulative probabilities:

```{r}
# discrete proportion of each response value
pr_k <-table(d$response)/nrow(d)

# cumsum converts to cumulative proportions
cum_pr_k <-cumsum(pr_k)

# plot
plot( 1:7,cum_pr_k,type="b",xlab="response",
ylab="cumulative proportion",ylim=c(0,1))
```

log cumulative odds:

```{r}
logit <-function(x)log(x/(1-x)) #convenience function
round( lco<-logit(cum_pr_k),2)
```

fit models:

```{r}
m12.4 <-ulam(
alist(
R ~dordlogit(0,cutpoints),
cutpoints ~dnorm(0,1.5)
) ,data=list(R=d$response),chains=4,cores=4)

m12.4q <-quap(
alist(
response ~dordlogit(0,c(a1,a2,a3,a4,a5,a6)),
c(a1,a2,a3,a4,a5,a6) ~dnorm(0,1.5)
) ,data=d,start=list(a1=-2,a2=-1,a3=0,a4=1,a5=2,a6=2.5))
```

posterior distribution

```{r}
precis( m12.4,depth=2)
```

get cumulative probabilities:

```{r}
round( inv_logit(coef(m12.4)),3)
```

## Adding predictor variables

```{r}
round( pk<-dordlogit(1:7,0,coef(m12.4)),2)
```

```{r}
sum( pk*(1:7))
```

```{r}
round( pk<-dordlogit(1:7,0,coef(m12.4)-0.5),2)
```

```{r}
sum( pk*(1:7))
```

fit model:

```{r}
dat <-list(
R =d$response,
A =d$action,
I =d$intention,
C =d$contact)
m12.5 <-ulam(
alist(
R ~dordlogit(phi,cutpoints),
phi <-bA*A+bC*C+BI*I,
BI <-bI+bIA*A+bIC*C,
c(bA,bI,bC,bIA,bIC) ~dnorm(0,0.5),
cutpoints ~dnorm(0,1.5)
) ,data=dat,chains=4,cores=4)
precis( m12.5)
```

plot posterior distribution:

```{r}
plot( precis(m12.5),xlim=c(-1.4,0))
```

plot posterior:

```{r}
plot( NULL,type="n",xlab="intention",ylab="probability",
xlim=c(0,1) ,ylim=c(0,1),xaxp=c(0,1,1),yaxp=c(0,1,2))

kA <-0   # value for action
kC <-0   # value for contact
kI <-0:1 # values of intention to calculate over
pdat <-data.frame(A=kA,C=kC,I=kI)
phi <-link(m12.5,data=pdat)$phi


post <-extract.samples(m12.5)
for (s in 1:50){
pk <-pordlogit(1:6,phi[s,],post$cutpoints[s,])
for (i in 1:6)lines(kI,pk[,i],col=grau(0.1))
}
```

show hist:

```{r}
kA <-0   # value for action
kC <-1   # value for contact
kI <-0:1 # values of intention to calculate over
pdat <-data.frame(A=kA,C=kC,I=kI)
s <-sim(m12.5,data=pdat)
simplehist( s,xlab="response")
```


















