---
title: "Ordered Categorical Predictors"
author: "Jasmin Capka"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

load data

```{r}
data(Trolley)
d <-Trolley
levels(d$edu)
```

make new values 

```{r}
edu_levels <-c(6,1,8,4,7,2,5,3)
d$edu_new <-edu_levels[d$edu]
```

simulate prior vectors:

```{r}
library(gtools)
set.seed(1805)
delta <-rdirichlet(10,alpha=rep(2,7))
str(delta)
```

plot

```{r}
h <-3
plot( NULL,xlim=c(1,7),ylim=c(0,0.4),xlab="index",ylab="probability")
for (i in 1:nrow(delta))lines(1:7,delta[i,],type="b",
pch=ifelse(i==h,16,1) ,lwd=ifelse(i==h,4,1.5),
col=ifelse(i==h,"black",col.alpha("black",0.7)) )
```

fit the model:

```{r}
dat <- list(
  R = d$response,
  action = d$action,
  intention = d$intention,
  contact = d$contact,
  E = as.integer(d$edu_new),  # edu_new as an index
  alpha = rep(2, 7) #delta prior
)

m12.6 <- ulam(
  alist(
    R ~ ordered_logistic(phi, kappa),
    phi <- bE * sum(delta_j[1:E]) + bA * action + bI * intention + bC * contact,
    kappa ~ normal(0, 1.5),
    c(bA, bI, bC, bE) ~ normal(0, 1),
    vector[8]:delta_j <<- append_row(0, delta),
    simplex[7]:delta ~ dirichlet(alpha)
  ),
  data = dat,
  chains = 4,
  cores = 4
)
```

```{r}
rep(2,7)
```

look at delta:

```{r}
delta_labels <-c("Elem","MidSch","SHS","HSG","SCol","Bach","Mast","Grad")
pairs( m12.6,pars="delta",labels=delta_labels)
```

make a model with education as continuous variable for comparison

```{r}
dat$edu_norm <-normalize(d$edu_new)
m12.7 <-ulam(
alist(
R ~ordered_logistic(mu,cutpoints),
mu <-bE*edu_norm+bA*action+bI*intention+bC*contact,
c(bA,bI,bC,bE) ~normal(0,1),
cutpoints ~normal(0,1.5)
), data=dat,chains=4,cores=4)
precis( m12.7)
```



















