---
title: "Overdispersed Counts"
author: "Jasmin Capka"
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Beta-binomial

```{r}
pbar <-0.5
theta <-2
curve( dbeta2(x,pbar,theta),from=0,to=1,
xlab="probability" ,ylab="Density")
```

Load and define data, fit model with ulam:

```{r}
data(UCBadmit)
d <-UCBadmit
d$gid <-ifelse(d$applicant.gender=="male",1L,2L)
dat <-list(A=d$admit,N=d$applications,gid=d$gid)
m12.1 <-ulam(
alist(
A ~dbetabinom(N,pbar,theta),
logit(pbar) <-a[gid],
a[gid] ~dnorm(0,1.5),
transpars> theta<<-phi+2.0,
phi ~dexp(1)
), data=dat,chains=4)
```

Look at model:

```{r}
post <-extract.samples(m12.1)
post$da <-post$a[,1]-post$a[,2]
precis( post,depth=2)
```

Plot beta-distribution

```{r}
gid <-2
# draw posterior mean beta distribution
curve( dbeta2(x,mean(logistic(post$a[,gid])),mean(post$theta)),from=0,to=1,
ylab="Density" ,xlab="probability admit",ylim=c(0,3),lwd=2)
# draw 50 beta distributions sampled from posterior
for (i in 1:50){
p <-logistic(post$a[i,gid])
theta <-post$theta[i]
curve( dbeta2(x,p,theta),add=TRUE,col=col.alpha("black",0.2))
}
mtext( "distribution of female admission rates")
```

Posterior validation check:

```{r}
postcheck( m12.1)
```

## Gamma-poisson

```{r}
data(Kline)
d <-Kline
d$P <-standardize(log(d$population))
d$contact_id <-ifelse(d$contact=="high",2L,1L)
dat2 <-list(
T =d$total_tools,
P =d$population,
cid =d$contact_id)
m12.2 <-ulam(
alist(
T ~dgampois(lambda,phi),
lambda <-exp(a[cid])*P^b[cid]/g,
a[cid] ~dnorm(1,1),
b[cid] ~dexp(1),
g ~dexp(1),
phi ~dexp(1)
), data=dat2,chains=4,log_lik=TRUE)
```































