---
title: "Marriage-Age-Happiness"
author: "Jasmin Capka"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
library(dagitty)
```

# Marriage-Age-Happiness

```{r load data}
d <- sim_happiness(seed = 1977, N_years = 1000)
precis(d)
```

```{r}
d2 <- d[d$age > 17,]  #onlyadults
d2$A <- (d2$age - 18) / (65 - 18)
```

```{r model with marriage and age on happiness}
d2$mid <- d2$married + 1
m6.9 <- quap(
  alist(
    happiness ~ dnorm(mu, sigma),
    mu <- a[mid] + bA * A,
    a[mid] ~ dnorm(0, 1),
    bA ~ dnorm(0, 2),
    sigma ~ dexp(1)
  ), data = d2)
precis(m6.9, depth = 2)
```

```{r model with only age on happiness}
m6.10 <- quap(
  alist(
    happiness ~ dnorm(mu, sigma),
    mu <- a + bA * A,
    a ~ dnorm(0, 1),
    bA ~ dnorm(0, 2),
    sigma ~ dexp(1)
  ), data = d2)
precis(m6.10)
```

# Childrens education
```{r define slopes}
N <- 200 # number of grandparent-parent-child triads
b_GP <- 1  #direct effect of G on P
b_GC <- 0  #direct effect of G on C
b_PC <- 1  #direct effect of P on C
b_U <- 2  #direct effect of U on P and C
```

```{r random observations}
set.seed(1)
U <- 2 * rbern(N, 0.5) - 1
G <- rnorm(N)
P <- rnorm(N, b_GP * G + b_U * U)
C <- rnorm(N, b_PC * P + b_GC * G + b_U * U)
d <- data.frame(C = C, P = P, G = G, U = U)
```

```{r model}
m6.11 <- quap(
  alist(
    C ~ dnorm(mu, sigma),
    mu <- a + b_PC * P + b_GC * G,
    a ~ dnorm(0, 1),
    c(b_PC, b_GC) ~ dnorm(0, 1),
    sigma ~ dexp(1)
  ), data = d)
precis(m6.11)
```

```{r model with U included}
m6.12 <- quap(
  alist(
    C ~ dnorm(mu, sigma),
    mu <- a + b_PC * P + b_GC * G + b_U * U,
    a ~ dnorm(0, 1),
    c(b_PC, b_GC, b_U) ~ dnorm(0, 1),
    sigma ~ dexp(1)
  ), data = d)
precis(m6.12)
```

















