---
title: "Multicollinearity"
author: "Jasmin Capka"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Multicollinear legs

```{r create leg data}
N <- 100  # number of individuals
set.seed(909)

height <- rnorm(N, 10, 2)  # sim total height of each

leg_prop <- runif(N, 0.4, 0.5)  #leg as proportion of height
leg_left <- leg_prop * height + rnorm(N, 0, 0.02) # sim left leg as proportion + error
leg_right <- leg_prop * height + rnorm(N, 0, 0.02) # sim right leg as proportion + error

# combine into dataframe
d <- data.frame(height, leg_left, leg_right)
```

```{r leg predictor}
m6.1 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + bl * leg_left + br * leg_right,
    a ~ dnorm(10, 100),
    bl ~ dnorm(2, 10),
    br ~ dnorm(2, 10),
    sigma ~ dexp(1)
  ), data = d)
precis(m6.1)
```

```{r plot leg predictor}
plot(precis(m6.1))
```

```{r joint posterior distribution for bl and br}
post <- extract.samples(m6.1)
plot(bl ~ br, post, col = col.alpha(rangi2, 0.1), pch = 16)
```

```{r sum of bl and br}
sum_blbr <- post$bl + post$br
dens(sum_blbr, col = rangi2, lwd = 2, xlab = "sum of bl and br")
```

```{r new leg predictor}
m6.2 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + bl * leg_left,
    a ~ dnorm(10, 100),
    bl ~ dnorm(2, 10),
    sigma ~ dexp(1)
  ), data = d)
precis(m6.2)
```

```{r plot new leg predictor}
plot(precis(m6.2))
```

## Multicollinear milk

```{r milk data}
library(rethinking)
data(milk)
d <- milk
d$K <- standardize(d$kcal.per.g)
d$F <- standardize(d$perc.fat)
d$L <- standardize(d$perc.lactose)
```

```{r bivariate regressions}
# kcal.per.g regressed on perc.fat
m6.3 <- quap(
  alist(
    K ~ dnorm(mu, sigma),
    mu <- a + bF * F,
    a ~ dnorm(0, 0.2),
    bF ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d)
# kcal.per.g regressed n perc.lactose
m6.4 <- quap(
  alist(
    K ~ dnorm(mu, sigma),
    mu <- a + bL * L,
    a ~ dnorm(0, 0.2),
    bL ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d)
precis(m6.3)
precis(m6.4)
```

```{r both predictors in same regressions}
m6.5 <- quap(
  alist(
    K ~ dnorm(mu, sigma),
    mu <- a + bF * F + bL * L,
    a ~ dnorm(0, 0.2),
    bF ~ dnorm(0, 0.5),
    bL ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ),
  data = d)
precis(m6.5)
```

```{r pairs}
pairs(~kcal.per.g + perc.fat + perc.lactose, data = d, col = rangi2)
```











